# Generated by Django 5.1.4 on 2024-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=4)),
                ('filter', models.CharField(blank=True, max_length=16)),
                ('image', models.CharField(blank=True, max_length=256)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('event', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
