# Generated by Django 5.1.4 on 2025-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_nextevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('championship', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('endurance', models.BooleanField(default=False)),
                ('sws', models.BooleanField(default=False)),
                ('heats', models.CharField(max_length=32)),
                ('ranking', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.CharField(blank=True, max_length=256)),
                ('info', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutme', models.TextField()),
            ],
        ),
    ]
