# Generated by Django 5.1.4 on 2025-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_calendarevent_sponsor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='heats',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='ranking',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
