# Generated by Django 5.1.4 on 2025-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_alter_calendarevent_heats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='age',
            field=models.CharField(default='16', max_length=2),
        ),
        migrations.AddField(
            model_name='website',
            name='height',
            field=models.CharField(default='1.84 m', max_length=6),
        ),
        migrations.AddField(
            model_name='website',
            name='weight',
            field=models.CharField(default='65 kg', max_length=6),
        ),
    ]
