# Generated by Django 5.1.4 on 2025-01-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_website_age_website_height_website_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
