# Generated by Django 5.1.4 on 2025-01-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_calendarevent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
