# Generated by Django 5.1.5 on 2025-02-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_calendarevent_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='heats',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
