# Generated by Django 5.2.4 on 2025-07-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_alter_calendarevent_heats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('gold', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('silver', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('bronze', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
